/*
 * levels: measures how loud each library sample plays, as DICE plays it,
 * and writes the table DICE levels them by (src/dsp/levels.c).
 *   tools/levels > src/dsp/levels.c
 * The tests measure again and fail if the table is out of date.
 */
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "levels.h"
#include "strut.h"

static float L[STRUT_SR * 4], R[STRUT_SR * 4];

static int by_float(const void *a, const void *b) {
    const float x = *(const float *)a, y = *(const float *)b;
    return x < y ? -1 : x > y;
}

int main(void) {
    smp_catalogue("src");
    static float db[SM_FILES], pk[SM_FILES], sorted[SM_FILES];
    int n = 0;
    for (int i = 0; i < smp_count(); i++) {
        if (!strncmp(smp_name(i), "Cycle ", 6)) continue;     /* DICE plays no cycles */
        db[i] = levels_measure(NT_TABLES + i, L, R, &pk[i]);
        sorted[n++] = db[i];
    }
    qsort(sorted, (size_t)n, sizeof(float), by_float);
    printf("/* Generated by tools/levels.c: each library sample's loudest 400 ms\n"
           " * and its peak, in dB, played as DICE plays it (levels.h). Do not\n"
           " * edit. */\n"
           "#include \"levels.h\"\n\n"
           "const float LEVELS_MEDIAN = %.1ff;\n\n"
           "const level_t LEVELS[] = {\n", (double)sorted[n / 2]);
    for (int i = 0; i < smp_count(); i++)
        if (strncmp(smp_name(i), "Cycle ", 6)) printf("    { \"%s\", %.1ff, %.1ff },\n", smp_name(i), (double)db[i], (double)pk[i]);
    printf("};\nconst int LEVELS_N = (int)(sizeof(LEVELS) / sizeof(LEVELS[0]));\n");
    return 0;
}
